server:
  port: 7000

spring:
  data:
    mongodb:
      host: 54.163.59.78
      port: 27017
      database: admin
      username: root
      password: password

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoints:
    web:
      exposure:
        exclude: '*'

